# Generated by Django 5.2 on 2026-03-29 09:48

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description_short', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('description_long', tinymce.models.HTMLField(blank=True, verbose_name='Полное описание')),
                ('longitude', models.DecimalField(decimal_places=14, max_digits=17, verbose_name='Долгота')),
                ('latitude', models.DecimalField(decimal_places=14, max_digits=17, verbose_name='Широта')),
            ],
        ),
    ]
