# Generated by Django 5.2 on 2026-03-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['images_order']},
        ),
        migrations.AddField(
            model_name='image',
            name='images_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядковый номер'),
        ),
    ]
