# Generated by Django 5.2 on 2026-05-19 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_place_description_long'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['images']},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='images_order',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='description_long',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='description_short',
            new_name='short_description',
        ),
    ]
