# Generated by Django 5.2 on 2026-06-03 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_image_options_rename_images_order_image_images_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['images_index']},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='images',
            new_name='images_index',
        ),
    ]
