# Generated by Django 5.2 on 2026-06-17 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_image_options_rename_images_image_images_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['index']},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='images_index',
            new_name='index',
        ),
    ]
